In [1]:
2**3

8

In [2]:
5*5

25

In [3]:
2*3

6

# Numpy Tutorial

######### Numpy

######Numpy

#####numpy

In [6]:
%timeit [i**2 for i in range(1,4)]

1.85 µs ± 78 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
%timeit [i**2 for i  in range(1,10000)]

4.24 ms ± 98.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4])

In [10]:
arr

array([1, 2, 3, 4])

In [11]:
arr.size

4

In [12]:
arr.ndim

1

In [13]:
arr.shape

(4,)

# reshape() function

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,-1)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#creation of 3D array 

In [18]:
arr = np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# zeros() , #ones(), #eye() , #diag() function

In [19]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [21]:
np.ones(2)

array([1., 1.])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
np.diag([5,5,5,5])

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5]])

# randint() and rand() function

In [26]:
np.random.randint(1,10,4)

array([1, 3, 3, 6])

In [27]:
np.random.rand(5)

array([0.71209179, 0.73249213, 0.2866432 , 0.13301599, 0.99560334])

In [28]:
np.random.randint(1,100,4)

array([45, 40, 95, 75])

In [29]:
np.random.randint(1,10,3)

array([5, 9, 5])

In [30]:
np.random.randint(1,10,10)

array([9, 1, 9, 7, 1, 3, 6, 5, 9, 1])

In [31]:
np.random.rand(5)

array([0.2079296 , 0.12786155, 0.97963961, 0.85158647, 0.20534832])

In [32]:
np.random.randint(1,100,10)

array([11, 45, 48, 74, 83, 45, 41, 66, 21, 66])

In [33]:
arr = np.random.randint(1,111,10).reshape(2,5)

In [34]:
arr

array([[ 36,   9,  64,  53, 104],
       [ 91,  72,  67, 106,  22]])

In [35]:
np.random.randn(5)

array([-0.52653838,  1.34862532,  0.18476374,  0.56622619, -0.77294418])

In [37]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

# indexing and slicing of numpy array

In [38]:
arr = np.array([1,2,3,4,5])

In [39]:
arr

array([1, 2, 3, 4, 5])

In [40]:
arr[2:]

array([3, 4, 5])

In [41]:
arr[-1:]

array([5])

In [42]:
arr[-3:]

array([3, 4, 5])

In [43]:
arr[1:4]

array([2, 3, 4])

In [44]:
arr[0:5:2]

array([1, 3, 5])

In [45]:
sliced_array = arr[2:4]
sliced_array

array([3, 4])

In [46]:
sliced_array[:] = 0
sliced_array

array([0, 0])

In [47]:
arr

array([1, 2, 0, 0, 5])

In [48]:
arr = np.array([1,2,3,4,5])

In [51]:
sliced_array = arr[2:4].copy()

In [52]:
sliced_array
arr

array([1, 2, 0, 0, 5])

In [53]:
sliced_array

array([0, 0])

#####reversing of an array

In [54]:
arr[::-1]

array([5, 0, 0, 2, 1])

In [55]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
matrix[0]

array([1, 2, 3])

In [57]:
matrix[1]

array([4, 5, 6])

In [58]:
matrix[0][2]

3

In [59]:
matrix[1][1]

5

In [60]:
matrix[1,1]

5

In [62]:
matrix[0,1]

2

In [63]:
matrix[:2,:2]

array([[1, 2],
       [4, 5]])

In [64]:
matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [65]:
np.random.seed(123)#it allows to generates same random number
arr=np.random.randint(1,101,25).reshape(5,5)
arr

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [66]:
arr[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [67]:
arr[2:,2:]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])

# view vs copy

In [68]:
#input[47]

#conditional selection 

In [69]:
arr=np.arange(1,11)

In [70]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [72]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [73]:
arr%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [74]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

#numpy axis

for rows put axis=1 and for coloumns put axis =0

In [75]:
arr = np.random.randint(1,10,9).reshape(3,3)

In [76]:
arr

array([[5, 8, 3],
       [5, 9, 1],
       [8, 4, 5]])

In [80]:
arr2 = np.random.randint(1,10,9).reshape(3,3)
arr2

array([[7, 2, 6],
       [7, 3, 2],
       [9, 4, 6]])

In [82]:
arr*arr2

array([[35, 16, 18],
       [35, 27,  2],
       [72, 16, 30]])

In [83]:
arr.dot(arr2)

array([[118,  46,  64],
       [107,  41,  54],
       [129,  48,  86]])

In [78]:
#calculate min element rowwise
np.min(arr,axis=1)

array([3, 1, 4])

In [79]:
#calculate max element columnwise
np.max(arr,axis=0)

array([8, 9, 5])

#hstacks() and vstack() function
these are used to concatinate two machine horizontally and vertically

In [84]:
matrix1 = np.random.randint(1,11,9).reshape(3,3)
matrix1

array([[1, 3, 7],
       [3, 5, 5],
       [7, 4, 1]])

In [85]:
matrix2= np.random.randint(50,100,9).reshape(3,3)

In [86]:
matrix2

array([[56, 64, 89],
       [61, 57, 51],
       [93, 87, 75]])

In [87]:
np.hstack((matrix1,matrix2))

array([[ 1,  3,  7, 56, 64, 89],
       [ 3,  5,  5, 61, 57, 51],
       [ 7,  4,  1, 93, 87, 75]])

In [88]:
np.vstack((matrix1,matrix2))

array([[ 1,  3,  7],
       [ 3,  5,  5],
       [ 7,  4,  1],
       [56, 64, 89],
       [61, 57, 51],
       [93, 87, 75]])