# Numpy Exercise

#### import numpy library

In [1]:
import numpy as np

#### create an array function

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

#### create an array containing numbers from 20 to 40 

In [8]:
arr2 = np.arange(20,40)
arr

array([1, 2, 3, 4, 5])

#### create an array which contain 10 elements and every element is 5

In [11]:
arr3 = np.ones(10)*5
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### create a 1-d array and then convert it into 3-D array

In [13]:
arr4 = np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
arr5 = np.random.randint(1,10,8).reshape(2,2,2)
arr5

array([[[9, 4],
        [5, 4]],

       [[9, 3],
        [3, 4]]])

#### creatte 2d array which contain random 25 numbers between 0and 1

In [16]:
arr6 = np.random.rand(25).reshape(5,5)
arr6

array([[0.28620396, 0.85080249, 0.37156282, 0.00879299, 0.89873369],
       [0.23667733, 0.81127576, 0.32797013, 0.75293606, 0.48051642],
       [0.4301379 , 0.72431235, 0.3009789 , 0.18441392, 0.02574371],
       [0.0577041 , 0.62553076, 0.35207035, 0.45490465, 0.51906742],
       [0.43908111, 0.84816031, 0.07929538, 0.44745113, 0.26059182]])

#### create array containing 20 random integer then replace every even number with -1

In [17]:
np.random.seed(123)
arr7 = np.random.randint(1,50,20)
arr7[arr7 % 2 == 0] = -1
arr7

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])

#### concatenate two 1-D array

In [18]:
arr8 = np.array([1,2,3,4,5])
arr9 = np.array([6,7,8,9])
np.hstack((arr8,arr9))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.concatenate((arr8,arr9))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])